# version: "3.9"
# services:
#   # MongoDB service
#   db:
#     image: mongo:latest
#     container_name: mongodb
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#   # Express.js service
#   app:
#     build: .
#     container_name: my-express-app
#     restart: always
#     environment:
#       MONGODB_URI: mongodb://root:example@db:27017/mydb
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
# volumes:
#   mongodb_data:
version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
